apiVersion: v1
kind: Service
metadata:
  name: trivy-service
  namespace: trivy
spec:
  type: NodePort
  selector:
    app: trivy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30084
