apiVersion: v1
kind: Service
metadata:
  name: harbor-service
  namespace: harbor
spec:
  type: NodePort
  selector:
    app: harbor
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  - port: 443
    targetPort: 443
    nodePort: 30443
